// ============================================
// Monstah Micro Learning — Ultra-Concise SmartyMe Content Library
// Strictly short, punchy 1-2 sentence cards!
// ============================================
import { Topic, Lesson, Quiz } from './types';

// ============ TOPICS ============
export const TOPICS: Topic[] = [
  {
    id: 'communication',
    name: 'Communication & Small Talk',
    icon: '🗣️',
    color: '#E67E22',
    description: 'Master first contact, networking, and effortless small talk.',
    lessonCount: 4,
  },
  {
    id: 'social-skills',
    name: 'Social Dynamics',
    icon: '🤝',
    color: '#FF6B6B',
    description: 'First impressions, body language, and charm.',
    lessonCount: 3,
  },
  {
    id: 'personal-growth',
    name: 'Personal Growth',
    icon: '🌱',
    color: '#4ECDC4',
    description: 'Productivity, habits, and focus secrets.',
    lessonCount: 3,
  },
  {
    id: 'philosophy',
    name: 'Philosophy & Wisdom',
    icon: '🏛️',
    color: '#8E44AD',
    description: 'Stoicism, mental models, and clear thinking.',
    lessonCount: 3,
  },
  {
    id: 'business',
    name: 'Business & Finance',
    icon: '💼',
    color: '#2ECC71',
    description: 'Negotiation, compounding, and startup tactics.',
    lessonCount: 3,
  },
  {
    id: 'health',
    name: 'Health & Wellness',
    icon: '🧘',
    color: '#1ABC9C',
    description: 'Sleep science, stress relief, and nutrition.',
    lessonCount: 3,
  },
  {
    id: 'technology',
    name: 'Tech & Future',
    icon: '🤖',
    color: '#34495E',
    description: 'AI, Bitcoin, cybersecurity, and quantum tech.',
    lessonCount: 4,
  },
  {
    id: 'history',
    name: 'History',
    icon: '📜',
    color: '#D35400',
    description: 'Pivotal moments that shaped humanity.',
    lessonCount: 3,
  },
  {
    id: 'science',
    name: 'Science',
    icon: '🔬',
    color: '#3498DB',
    description: 'Laws of nature and physics demystified.',
    lessonCount: 3,
  },
  {
    id: 'art',
    name: 'Art & Culture',
    icon: '🎨',
    color: '#E91E63',
    description: 'Masterpieces and creative movements.',
    lessonCount: 3,
  },
  {
    id: 'math',
    name: 'Mathematics',
    icon: '📐',
    color: '#9B59B6',
    description: 'Patterns, logic, and famous numbers.',
    lessonCount: 3,
  },
  {
    id: 'biology',
    name: 'Biology',
    icon: '🧬',
    color: '#27AE60',
    description: 'The inner workings of living organisms.',
    lessonCount: 3,
  },
  {
    id: 'geography',
    name: 'Geography',
    icon: '🌍',
    color: '#16A085',
    description: 'Incredible earth places and phenomena.',
    lessonCount: 3,
  },
  {
    id: 'space',
    name: 'Space & Cosmos',
    icon: '🚀',
    color: '#2C3E50',
    description: 'Black holes, planets, and galaxies.',
    lessonCount: 3,
  },
  {
    id: 'psychology',
    name: 'Psychology',
    icon: '🧠',
    color: '#F39C12',
    description: 'Mind biases and human behavior.',
    lessonCount: 3,
  },
];

// ============ LESSONS (Ultra-Short SmartyMe Format) ============
export const LESSONS: Lesson[] = [
  // --- SOCIAL / COMMUNICATION ---
  {
    id: 'social-1',
    topicId: 'social-skills',
    title: 'Meeting Someone for First Time',
    subtitle: 'First impressions',
    duration: 3,
    difficulty: 'beginner',
    order: 1,
    cards: [
      {
        id: 'soc1-1',
        type: 'scenario',
        contextHeader: '📋 Scenario Setup',
        title: 'Entering a Crowded Room',
        content: 'You walk into a networking mixer alone. You notice someone standing near the refreshment table looking around. You have 7 seconds before subconscious impression filters lock in.',
        emoji: '⏱️',
      },
      {
        id: 'soc1-2',
        type: 'script',
        contextHeader: '💬 What to Say',
        title: 'First Contact Phrasing',
        content: 'Compare how different openers establish immediate warmth and safety:',
        examples: [
          {
            label: 'Awkward Line',
            text: 'So... pretty crowded here, huh? I hate these things.',
            status: 'bad',
          },
          {
            label: 'Standard Line',
            text: 'Hi, I’m Alex. What do you do for work?',
            status: 'good',
          },
          {
            label: 'Winning Script',
            text: 'Hi! I’m Alex. I haven’t tried the roast here yet—is it as good as everyone says?',
            status: 'best',
          },
        ],
        emoji: '✨',
      },
      {
        id: 'soc1-3',
        type: 'explanation',
        contextHeader: '💡 Strategy Breakdown',
        title: 'The TRIO Rule',
        content: 'Touch with a warm handshake, Radiate eye contact with a smile, and Inquire about their observation.',
        emoji: '🤯',
        highlight: 'Radiate eye contact with a smile',
      },
      {
        id: 'soc1-4',
        type: 'keyPoint',
        contextHeader: '🔑 Golden Rule',
        title: 'Key Takeaway',
        content: 'Focus entirely on making the other person feel interesting and safe.',
        emoji: '🔑',
      },
    ],
  },
  {
    id: 'comm-first-contact',
    topicId: 'communication',
    title: 'First Contact & Icebreakers',
    subtitle: 'Breaking the ice',
    duration: 3,
    difficulty: 'beginner',
    order: 1,
    cards: [
      {
        id: 'cfc-1',
        type: 'scenario',
        contextHeader: '📋 Scenario Setup',
        title: 'The Coffee Shop Queue',
        content: 'You are waiting in line at a busy cafe next to someone reading a book on design. You want to start a conversation naturally without feeling pushy.',
        emoji: '❄️',
      },
      {
        id: 'cfc-2',
        type: 'script',
        contextHeader: '💬 What to Say',
        title: 'Observational Opener',
        content: 'Replace generic small talk with shared environmental observations:',
        examples: [
          {
            label: 'Generic Line',
            text: 'Nice weather today, right?',
            status: 'bad',
          },
          {
            label: 'Winning Script',
            text: 'Excuse me, I noticed that cover—is that the new edition on UX architecture?',
            status: 'best',
          },
        ],
        emoji: '🗣️',
      },
      {
        id: 'cfc-3',
        type: 'didYouKnow',
        contextHeader: '🧠 Behavioral Insight',
        title: 'Did You Know?',
        content: 'Starting with a warm observational statement reduces social friction by 45%.',
        emoji: '🤯',
        highlight: 'reduces social friction by 45%',
      },
      {
        id: 'cfc-4',
        type: 'keyPoint',
        contextHeader: '🔑 Golden Rule',
        title: 'Key Takeaway',
        content: 'First contact is about establishing mutual safety and shared context.',
        emoji: '🔑',
      },
    ],
  },
  {
    id: 'comm-small-talk',
    topicId: 'communication',
    title: 'Mastering Effortless Small Talk',
    subtitle: 'Flowing conversations',
    duration: 4,
    difficulty: 'beginner',
    order: 2,
    cards: [
      {
        id: 'cst-1',
        type: 'scenario',
        contextHeader: '📋 Scenario Setup',
        title: 'Elevator With a Senior Lead',
        content: 'You step into an elevator with a company VP. You have 30 seconds of quiet ride time. You want to initiate dialogue that feels authentic.',
        emoji: '🧵',
      },
      {
        id: 'cst-2',
        type: 'script',
        contextHeader: '💬 What to Say',
        title: 'Conversational Threading',
        content: 'Pick a recent victory or project topic to hook their interest:',
        examples: [
          {
            label: 'Timid Line',
            text: 'Mondays... am I right?',
            status: 'bad',
          },
          {
            label: 'Winning Script',
            text: 'Congrats on the Q3 product release! What part of that build was most exciting for your team?',
            status: 'best',
          },
        ],
        emoji: '🚗',
      },
      {
        id: 'cst-3',
        type: 'explanation',
        contextHeader: '💡 The FORD Framework',
        title: 'Topic Generators',
        content: 'When stuck for conversation depth, inquire about Family, Occupation, Recreation, or Dreams.',
        emoji: '🤯',
        highlight: 'Family, Occupation, Recreation, Dreams',
      },
      {
        id: 'cst-4',
        type: 'keyPoint',
        contextHeader: '🔑 Golden Rule',
        title: 'Key Takeaway',
        content: 'Small talk is just the gateway to discovering shared passions.',
        emoji: '🔑',
      },
    ],
  },
  {
    id: 'comm-nice-person',
    topicId: 'communication',
    title: 'Stop Speaking Like a Nice Person',
    subtitle: 'Assertive presence',
    duration: 4,
    difficulty: 'intermediate',
    order: 3,
    cards: [
      {
        id: 'cnp-1',
        type: 'scenario',
        contextHeader: '📋 Scenario Setup',
        title: 'Handing off a Urgent Task',
        content: 'Your project deadline was moved up to 3 PM. A teammate sends an incomplete report. You need section 2 updated quickly without damaging working rapport.',
        emoji: '💪',
      },
      {
        id: 'cnp-2',
        type: 'script',
        contextHeader: '💬 What to Say',
        title: 'Apology vs Gratitude Phrasing',
        content: 'Notice how dropping apology words transforms authority and respect:',
        examples: [
          {
            label: 'Over-Apologetic',
            text: 'Sorry to bother you! So sorry, but whenever you get a chance could you maybe re-check section 2?',
            status: 'bad',
          },
          {
            label: 'Winning Script',
            text: 'Thanks for sending this over! To hit our 3 PM client deadline, please update section 2 with Q3 figures by 1 PM.',
            status: 'best',
          },
        ],
        emoji: '🔄',
      },
      {
        id: 'cnp-3',
        type: 'didYouKnow',
        contextHeader: '🧠 Voice Authority',
        title: 'Did You Know?',
        content: 'Ending sentences with upward inflections (upspeak) drops perceived authority by 30%.',
        emoji: '🤯',
        highlight: 'drops perceived authority by 30%',
      },
      {
        id: 'cnp-4',
        type: 'keyPoint',
        contextHeader: '🔑 Golden Rule',
        title: 'Key Takeaway',
        content: 'High-status communication combines genuine warmth with direct clarity.',
        emoji: '🔑',
      },
    ],
  },
  {
    id: 'comm-networking',
    topicId: 'communication',
    title: 'Navigating Networking Events',
    subtitle: 'Room exits & entry',
    duration: 4,
    difficulty: 'intermediate',
    order: 4,
    cards: [
      {
        id: 'cnet-1',
        type: 'scenario',
        contextHeader: '📋 Scenario Setup',
        title: 'Leaving a Long Conversation',
        content: 'You’ve been speaking with an attendee for 15 minutes. The conversation has reached a natural lull and you want to meet other guests gracefully.',
        emoji: '👔',
      },
      {
        id: 'cnet-2',
        type: 'script',
        contextHeader: '💬 What to Say',
        title: 'The Graceful Exit Line',
        content: 'Use a value statement followed by an action transition:',
        examples: [
          {
            label: 'Awkward Exit',
            text: 'Uh... okay I guess I have to go to the bathroom now, bye.',
            status: 'bad',
          },
          {
            label: 'Winning Script',
            text: 'It was fantastic learning about your project! I’m going to grab a drink now—let’s connect on LinkedIn before we leave.',
            status: 'best',
          },
        ],
        emoji: '🚪',
      },
      {
        id: 'cnet-3',
        type: 'explanation',
        contextHeader: '💡 Formation Secret',
        title: 'V-Shape Entry',
        content: 'Look for groups of 3 standing in an open V-shape rather than a closed circle to enter naturally.',
        emoji: '🤯',
        highlight: 'open V-shape rather than a closed circle',
      },
      {
        id: 'cnet-4',
        type: 'keyPoint',
        contextHeader: '🔑 Golden Rule',
        title: 'Key Takeaway',
        content: 'Collect stories and connections, not sales pitches.',
        emoji: '🔑',
      },
    ],
  },
  {
    id: 'tech-digital-money',
    topicId: 'technology',
    title: 'Demystifying Digital Money',
    subtitle: 'Bitcoin & Blockchain',
    duration: 3,
    difficulty: 'beginner',
    order: 1,
    cards: [
      {
        id: 'tdm-1',
        type: 'fact',
        title: 'Money Without Central Banks',
        content: 'Cryptocurrency is digital money secured by cryptography operating on decentralized peer-to-peer networks.',
        emoji: '🌐',
      },
      {
        id: 'tdm-2',
        type: 'explanation',
        title: 'The Immutable Ledger',
        content: 'Transactions are recorded on a blockchain—a digital ledger distributed across thousands of computers that can never be altered.',
        emoji: '⛓️',
      },
      {
        id: 'tdm-3',
        type: 'didYouKnow',
        title: 'Did You Know?',
        content: 'Bitcoin supply is hard-capped at 21 million coins.',
        emoji: '🤯',
        highlight: 'hard-capped at 21 million coins',
      },
      {
        id: 'tdm-4',
        type: 'keyPoint',
        title: 'Key Takeaway',
        content: 'Crypto replaces trust in central institutions with cryptographic math.',
        emoji: '🔑',
      },
    ],
  },

  // --- ACADEMICS & OTHER TOPICS (All Crisp SmartyMe Style) ---
  { id: 'social-2', topicId: 'social-skills', title: 'Active Listening Secrets', subtitle: 'Feel heard', duration: 3, difficulty: 'beginner', order: 2, cards: [{ id: 'soc2-1', type: 'fact', title: 'Listening Intent', content: 'Most people listen to reply, not to understand.', emoji: '👂' }, { id: 'soc2-2', type: 'explanation', title: 'Mirroring', content: 'Repeat the last 2-3 words with a curious inflection.', emoji: '🪞' }, { id: 'soc2-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Pausing 2s makes you look 40% more thoughtful.', emoji: '🤯', highlight: 'Pausing 2s makes you look 40% more thoughtful' }, { id: 'soc2-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Great listeners ask insightful follow-ups.', emoji: '🔑' }] },
  { id: 'social-3', topicId: 'social-skills', title: 'Overcoming Social Anxiety', subtitle: 'Room confidence', duration: 4, difficulty: 'intermediate', order: 3, cards: [{ id: 'soc3-1', type: 'fact', title: 'Spotlight Effect', content: 'We overestimate how much others notice our flaws.', emoji: '💡' }, { id: 'soc3-2', type: 'explanation', title: 'Shift Focus', content: 'Focus on observing the room instead of your heartbeat.', emoji: '🎯' }, { id: 'soc3-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Power posing for 2m lowers cortisol by 25%.', emoji: '🤯', highlight: 'lowers cortisol by 25%' }, { id: 'soc3-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Action precedes confidence.', emoji: '🔑' }] },
  {
    id: 'growth-1',
    topicId: 'personal-growth',
    title: 'Beating Procrastination',
    subtitle: '2-Minute Rule',
    duration: 4,
    difficulty: 'beginner',
    order: 1,
    cards: [
      {
        id: 'pg1-1',
        type: 'scenario',
        contextHeader: '📋 Scenario Setup',
        title: 'The Dreaded Blank Document',
        content: 'It’s 8 PM. You’ve been staring at a blank slide deck for an hour. Every time you open the tab, your brain urges you to check your phone or clean your desk.',
        emoji: '⏳',
      },
      {
        id: 'pg1-2',
        type: 'script',
        contextHeader: '💬 What to Say to Yourself',
        title: 'Breaking the Starting Friction',
        content: 'Compare how self-talk triggers or breaks procrastination friction:',
        examples: [
          {
            label: 'Friction-Heavy Self-Talk',
            text: 'I have to finish this entire 20-slide presentation tonight before I can rest.',
            status: 'bad',
          },
          {
            label: 'Winning Script',
            text: 'I’m only going to write the title and slide 1 outline for 2 minutes. Then I can stop if I want to.',
            status: 'best',
          },
        ],
        emoji: '⏱️',
      },
      {
        id: 'pg1-3',
        type: 'didYouKnow',
        contextHeader: '🧠 Brain Science',
        title: 'Did You Know?',
        content: 'Procrastination is an emotion regulation issue, not a time management flaw.',
        emoji: '🤯',
        highlight: 'emotion regulation issue',
      },
      {
        id: 'pg1-4',
        type: 'keyPoint',
        contextHeader: '🔑 Golden Rule',
        title: 'Key Takeaway',
        content: 'Action precedes motivation. Lower the starting barrier to 2 minutes.',
        emoji: '🔑',
      },
    ],
  },
  { id: 'growth-2', topicId: 'personal-growth', title: 'Atomic Habits', subtitle: '1% compounding', duration: 4, difficulty: 'beginner', order: 2, cards: [{ id: 'pg2-1', type: 'fact', title: '1% Rule', content: '1% daily improvement makes you 37x better in one year.', emoji: '📈' }, { id: 'pg2-2', type: 'explanation', title: 'Habit Stacking', content: 'Attach a new desired habit onto an established daily routine.', emoji: '🥞' }, { id: 'pg2-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Environment design is 5x more effective than willpower.', emoji: '🤯', highlight: 'Environment design is 5x more effective' }, { id: 'pg2-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Build systems, not just goals.', emoji: '🔑' }] },
  { id: 'growth-3', topicId: 'personal-growth', title: 'Deep Work Strategy', subtitle: 'Focus secrets', duration: 5, difficulty: 'intermediate', order: 3, cards: [{ id: 'pg3-1', type: 'fact', title: 'Attention Residue', content: 'Multitasking leaves cognitive residue that degrades performance.', emoji: '🧠' }, { id: 'pg3-2', type: 'explanation', title: 'Time Blocks', content: 'Schedule uninterrupted 90-minute blocks for deep cognitive work.', emoji: '📅' }, { id: 'pg3-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Interruption takes 23 minutes to recover full focus.', emoji: '🤯', highlight: 'takes 23 minutes to recover full focus' }, { id: 'pg3-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Deep work is rare and valuable.', emoji: '🔑' }] },
  { id: 'philosophy-1', topicId: 'philosophy', title: 'Stoicism', subtitle: 'Mind control', duration: 4, difficulty: 'beginner', order: 1, cards: [{ id: 'ph1-1', type: 'fact', title: 'Control', content: 'Only your own mind, choices, and reactions are in your control.', emoji: '🛡️' }, { id: 'ph1-2', type: 'explanation', title: 'Amor Fati', content: 'Embrace every hardship as fuel for growth.', emoji: '🔥' }, { id: 'ph1-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Marcus Aurelius wrote Meditations as private notes.', emoji: '🤯', highlight: 'wrote Meditations as private notes' }, { id: 'ph1-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Tranquility comes from acceptance.', emoji: '🔑' }] },
  { id: 'philosophy-2', topicId: 'philosophy', title: 'Mental Models', subtitle: 'Clear thinking', duration: 4, difficulty: 'intermediate', order: 2, cards: [{ id: 'ph2-1', type: 'fact', title: 'First Principles', content: 'Break problems down to basic fundamental truths.', emoji: '🧱' }, { id: 'ph2-2', type: 'explanation', title: 'Inversion', content: 'Figure out how to fail, then avoid those exact actions.', emoji: '🔄' }, { id: 'ph2-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Warren Buffett uses 100 core mental models.', emoji: '🤯', highlight: 'uses 100 core mental models' }, { id: 'ph2-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Models improve decision speed.', emoji: '🔑' }] },
  { id: 'philosophy-3', topicId: 'philosophy', title: 'Critical Thinking', subtitle: 'Logical fallacies', duration: 4, difficulty: 'intermediate', order: 3, cards: [{ id: 'ph3-1', type: 'fact', title: 'Fallacies', content: 'Ad Hominem attacks the person instead of the argument.', emoji: '🕵️' }, { id: 'ph3-2', type: 'explanation', title: 'Occam\'s Razor', content: 'The simplest explanation with fewest assumptions is usually right.', emoji: '🪒' }, { id: 'ph3-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Confirmation bias filters out contradicting facts.', emoji: '🤯', highlight: 'filters out contradicting facts' }, { id: 'ph3-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Question your own assumptions.', emoji: '🔑' }] },
  {
    id: 'business-1',
    topicId: 'business',
    title: 'Negotiate Your Salary: Walk Out With More',
    subtitle: 'Walk out with more',
    duration: 4,
    difficulty: 'beginner',
    order: 1,
    cards: [
      {
        id: 'biz1-1',
        type: 'scenario',
        contextHeader: '📋 Scenario Setup',
        title: 'The Thursday Pay Review',
        content: 'Late Thursday. You’re heading into a meeting with your manager Adrian. For months you’ve been handling the two hardest clients who almost left in spring. You kept them. You also picked up the work of a coworker who quit.',
        emoji: '💼',
      },
      {
        id: 'biz1-2',
        type: 'script',
        contextHeader: '💬 What to Say',
        title: 'Framing Your Compensation Request',
        content: 'How many times have you left that meeting with nothing but "we’ll see"? Compare these three actual scripts:',
        examples: [
          {
            label: 'Frustrated Phrasing',
            text: 'Honestly, I feel like I’m doing way more than what I was hired for, and it’s frustrating that nothing has changed.',
            status: 'bad',
          },
          {
            label: 'Timid Phrasing',
            text: 'I wanted to talk about the raise again. I know last time you said the budget was tight, but I was hoping we could look at it again.',
            status: 'good',
          },
          {
            label: 'Winning Script',
            text: 'I want to talk about my pay. Before we get into numbers, let me walk you through what I’ve been doing. I think it’ll make this easier for both of us.',
            status: 'best',
          },
        ],
        emoji: '🗣️',
      },
      {
        id: 'biz1-3',
        type: 'explanation',
        contextHeader: '💡 Strategy Breakdown',
        title: 'Anchor Value Before Numbers',
        content: 'Framing your contribution before stating a figure removes defensive pushback and anchors the discussion on proven impact.',
        emoji: '🧠',
        highlight: 'anchors the discussion on proven impact',
      },
      {
        id: 'biz1-4',
        type: 'keyPoint',
        contextHeader: '🔑 Golden Rule',
        title: 'Key Takeaway',
        content: 'Never ask for money based on personal need—always anchor on value delivered.',
        emoji: '🔑',
      },
    ],
  },
  { id: 'business-2', topicId: 'business', title: 'Compound Interest', subtitle: 'Wealth engine', duration: 3, difficulty: 'beginner', order: 2, cards: [{ id: 'biz2-1', type: 'fact', title: 'Compounding', content: 'Earning interest on top of past interest creates exponential growth.', emoji: '💰' }, { id: 'biz2-2', type: 'explanation', title: 'Rule of 72', content: 'Divide 72 by interest rate to find years needed to double money.', emoji: '🔢' }, { id: 'biz2-3', type: 'didYouKnow', title: 'Did You Know?', content: '99% of Buffett\'s wealth accumulated after age 50.', emoji: '🤯', highlight: '99% of Buffett\'s wealth accumulated after 50' }, { id: 'biz2-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Time in market beats timing market.', emoji: '🔑' }] },
  { id: 'business-3', topicId: 'business', title: 'Lean Startup', subtitle: 'MVP strategy', duration: 4, difficulty: 'intermediate', order: 3, cards: [{ id: 'biz3-1', type: 'fact', title: 'MVP Concept', content: 'Build the simplest product version to collect validated learning.', emoji: '🚀' }, { id: 'biz3-2', type: 'explanation', title: 'Feedback Loop', content: 'Build, measure real usage, and iterate fast.', emoji: '🔄' }, { id: 'biz3-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Airbnb MVP was a simple blog post for air mattresses.', emoji: '🤯', highlight: 'Airbnb MVP was a simple blog post' }, { id: 'biz3-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Validate demand before heavy investing.', emoji: '🔑' }] },
  { id: 'health-1', topicId: 'health', title: 'Sleep Science', subtitle: 'Circadian rhythms', duration: 4, difficulty: 'beginner', order: 1, cards: [{ id: 'hea1-1', type: 'fact', title: 'Circadian Clock', content: 'Morning light boosts cortisol; darkness triggers sleep melatonin.', emoji: '☀️' }, { id: 'hea1-2', type: 'explanation', title: 'Sleep Hygiene', content: 'Keep bedroom cool (~65°F) and avoid blue screens 1 hour before bed.', emoji: '🌙' }, { id: 'hea1-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Deep sleep flushes metabolic waste toxins from the brain.', emoji: '🤯', highlight: 'flushes metabolic waste toxins from brain' }, { id: 'hea1-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Sleep is a non-negotiable health pillar.', emoji: '🔑' }] },
  { id: 'health-2', topicId: 'health', title: 'Mindfulness', subtitle: 'Stress relief', duration: 3, difficulty: 'beginner', order: 2, cards: [{ id: 'hea2-1', type: 'fact', title: 'Amygdala Response', content: 'Your threat center activates fight-or-flight for stress.', emoji: '🚨' }, { id: 'hea2-2', type: 'explanation', title: 'Physiological Sigh', content: '2 quick inhales + 1 long exhale instantly lowers heart rate.', emoji: '🫁' }, { id: 'hea2-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Daily meditation physically shrinks the amygdala.', emoji: '🤯', highlight: 'physically shrinks the amygdala' }, { id: 'hea2-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Breath directly controls nervous system.', emoji: '🔑' }] },
  { id: 'health-3', topicId: 'health', title: 'Nutrition Myths', subtitle: 'Gut health', duration: 4, difficulty: 'intermediate', order: 3, cards: [{ id: 'hea3-1', type: 'fact', title: 'Macros vs Micros', content: 'Protein, carbs, and fats supply fuel; micronutrients run cells.', emoji: '🥗' }, { id: 'hea3-2', type: 'explanation', title: 'Bliss Point Trap', content: 'Processed foods combine sugar, salt, and fat to bypass satiety.', emoji: '🍔' }, { id: 'hea3-3', type: 'didYouKnow', title: 'Did You Know?', content: '90% of serotonin is produced in the gut.', emoji: '🤯', highlight: '90% of serotonin is produced in the gut' }, { id: 'hea3-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Eat real whole foods for gut health.', emoji: '🔑' }] },
  { id: 'tech-1', topicId: 'technology', title: 'How AI Works', subtitle: 'Neural nets & LLMs', duration: 4, difficulty: 'beginner', order: 2, cards: [{ id: 'tec1-1', type: 'fact', title: 'Pattern Engines', content: 'AI predicts likely outputs from massive data patterns.', emoji: '🤖' }, { id: 'tec1-2', type: 'explanation', title: 'Token Prediction', content: 'LLMs predict the next word token in text.', emoji: '💬' }, { id: 'tec1-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Transformers paper was published by Google in 2017.', emoji: '🤯', highlight: 'Transformers paper published in 2017' }, { id: 'tec1-4', type: 'keyPoint', title: 'Key Takeaway', content: 'AI is a human multiplier.', emoji: '🔑' }] },
  { id: 'tech-2', topicId: 'technology', title: 'Cybersecurity Essentials', subtitle: 'Digital safety', duration: 3, difficulty: 'beginner', order: 3, cards: [{ id: 'tec2-1', type: 'fact', title: 'Human Risk', content: 'Over 80% of security breaches involve human error.', emoji: '🔐' }, { id: 'tec2-2', type: 'explanation', title: 'Password Managers', content: 'Use unique 20-character passwords and enable 2FA.', emoji: '📱' }, { id: 'tec2-3', type: 'didYouKnow', title: 'Did You Know?', content: 'A 14-character passphrase takes 100,000 years to crack.', emoji: '🤯', highlight: 'takes 100,000 years to crack' }, { id: 'tec2-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Never reuse passwords across sites.', emoji: '🔑' }] },
  { id: 'tech-3', topicId: 'technology', title: 'Quantum Computing', subtitle: 'Qubits', duration: 4, difficulty: 'intermediate', order: 4, cards: [{ id: 'tec3-1', type: 'fact', title: 'Qubit States', content: 'Qubits exist as 0, 1, or both simultaneously.', emoji: '⚛️' }, { id: 'tec3-2', type: 'explanation', title: 'Superposition', content: 'Evaluates massive possibilities in parallel.', emoji: '⚡' }, { id: 'tec3-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Einstein called entanglement "spooky action at a distance."', emoji: '🤯', highlight: 'spooky action at a distance' }, { id: 'tec3-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Revolutionizes cryptography.', emoji: '🔑' }] },
  { id: 'history-1', topicId: 'history', title: 'Fall of Rome', subtitle: 'Empire collapse', duration: 4, difficulty: 'beginner', order: 1, cards: [{ id: 'h1-1', type: 'fact', title: 'Western Rome', content: 'Fell in 476 AD when Odoacer deposed Romulus Augustulus.', emoji: '⚔️' }, { id: 'h1-2', type: 'explanation', title: 'Centuries of Decline', content: 'Caused by political corruption and invasions.', emoji: '📉' }, { id: 'h1-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Rome held 21% of world population at peak.', emoji: '🤯', highlight: 'Rome held 21% of world population' }, { id: 'h1-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Eastern Rome lasted until 1453.', emoji: '🔑' }] },
  { id: 'history-2', topicId: 'history', title: 'Silk Road', subtitle: 'Trade network', duration: 3, difficulty: 'beginner', order: 2, cards: [{ id: 'h2-1', type: 'fact', title: '4,000-Mile Network', content: 'Connected China to Mediterranean from 130 BC to 1453 AD.', emoji: '🛤️' }, { id: 'h2-2', type: 'explanation', title: 'Cultural Exchange', content: 'Spices, silk, and religions spread along trade routes.', emoji: '📦' }, { id: 'h2-3', type: 'didYouKnow', title: 'Did You Know?', content: 'The term "Silk Road" was coined in 1877.', emoji: '🤯', highlight: 'coined in 1877' }, { id: 'h2-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Early globalization.', emoji: '🔑' }] },
  { id: 'history-3', topicId: 'history', title: 'French Revolution', subtitle: '1789 uprising', duration: 5, difficulty: 'intermediate', order: 3, cards: [{ id: 'h3-1', type: 'fact', title: 'Bastille Storming', content: 'On July 14, 1789, Parisians stormed the royal Bastille fortress.', emoji: '🏰' }, { id: 'h3-2', type: 'explanation', title: 'Inequality', content: 'The Third Estate (98% of people) had zero political power.', emoji: '⚖️' }, { id: 'h3-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Marie Antoinette never said "Let them eat cake."', emoji: '🤯', highlight: 'never said Let them eat cake' }, { id: 'h3-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Introduced modern citizenship rights.', emoji: '🔑' }] },
  { id: 'science-1', topicId: 'science', title: 'How Gravity Works', subtitle: 'Mass attraction', duration: 4, difficulty: 'beginner', order: 1, cards: [{ id: 's1-1', type: 'fact', title: 'Mass Pull', content: 'Every mass attracts every other mass in the universe.', emoji: '🌎' }, { id: 's1-2', type: 'explanation', title: 'Spacetime Curvature', content: 'Einstein proved gravity is the curvature of spacetime.', emoji: '🕳️' }, { id: 's1-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Earth spin without gravity flings you at 1,000 mph.', emoji: '🤯', highlight: 'flings you at 1,000 mph' }, { id: 's1-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Holds cosmic systems together.', emoji: '🔑' }] },
  { id: 'science-2', topicId: 'science', title: 'States of Matter', subtitle: 'Plasma & solids', duration: 3, difficulty: 'beginner', order: 2, cards: [{ id: 's2-1', type: 'fact', title: 'Kinetic Energy', content: 'Solid, liquid, and gas depend on particle kinetic energy.', emoji: '🧊' }, { id: 's2-2', type: 'explanation', title: 'Plasma', content: 'Superheated ionized gas making up 99% of visible universe.', emoji: '⚡' }, { id: 's2-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Glass is an amorphous solid, not a liquid.', emoji: '🤯', highlight: 'Glass is an amorphous solid' }, { id: 's2-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Heat dictates state.', emoji: '🔑' }] },
  { id: 'science-3', topicId: 'science', title: 'Speed of Light', subtitle: '299,792,458 m/s', duration: 4, difficulty: 'intermediate', order: 3, cards: [{ id: 's3-1', type: 'fact', title: 'Fastest Speed', content: 'Light travels fast enough to circle Earth 7.5 times per second.', emoji: '💡' }, { id: 's3-2', type: 'explanation', title: 'Cosmic Limit', content: 'Infinite energy is required for mass to reach light speed.', emoji: '🚫' }, { id: 's3-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Sunlight takes 8m 20s to reach Earth.', emoji: '🤯', highlight: 'Sunlight takes 8m 20s' }, { id: 's3-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Universal speed limit.', emoji: '🔑' }] },
  { id: 'art-1', topicId: 'art', title: 'The Mona Lisa', subtitle: 'Da Vinci', duration: 3, difficulty: 'beginner', order: 1, cards: [{ id: 'a1-1', type: 'fact', title: 'Small Portrait', content: 'Painted by Leonardo da Vinci between 1503-1519.', emoji: '🖼️' }, { id: 'a1-2', type: 'explanation', title: 'Sfumato', content: 'Subtle shading technique creates the mysterious smile.', emoji: '😊' }, { id: 'a1-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Became world-famous after 1911 Louvre theft.', emoji: '🤯', highlight: 'famous after 1911 Louvre theft' }, { id: 'a1-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Revolutionized portraiture.', emoji: '🔑' }] },
  { id: 'art-2', topicId: 'art', title: 'Impressionism', subtitle: 'Monet & Degas', duration: 4, difficulty: 'beginner', order: 2, cards: [{ id: 'a2-1', type: 'fact', title: 'Outdoor Light', content: 'Captured fleeting outdoor light and motion.', emoji: '🌅' }, { id: 'a2-2', type: 'explanation', title: 'Monet Impression', content: 'Named after a critic insulted Monet\'s "Impression, Sunrise".', emoji: '🎭' }, { id: 'a2-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Collapsible paint tubes in 1841 made outdoor painting possible.', emoji: '🤯', highlight: 'Collapsible paint tubes in 1841' }, { id: 'a2-4', type: 'keyPoint', title: 'Key Takeaway', content: 'First modern art movement.', emoji: '🔑' }] },
  { id: 'art-3', topicId: 'art', title: 'Ukiyo-e', subtitle: 'Japanese prints', duration: 4, difficulty: 'intermediate', order: 3, cards: [{ id: 'a3-1', type: 'fact', title: 'Woodblock Prints', content: 'Woodblock art like Hokusai\'s Great Wave.', emoji: '🌊' }, { id: 'a3-2', type: 'explanation', title: 'Mass Art', content: 'Affordable art for ordinary citizens.', emoji: '🖨️' }, { id: 'a3-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Ukiyo-e prints were used as export wrapping paper.', emoji: '🤯', highlight: 'used as export wrapping paper' }, { id: 'a3-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Profoundly shaped Impressionism.', emoji: '🔑' }] },
  { id: 'math-1', topicId: 'math', title: 'The Golden Ratio', subtitle: 'φ ≈ 1.618', duration: 4, difficulty: 'beginner', order: 1, cards: [{ id: 'm1-1', type: 'fact', title: 'Phi Proportion', content: 'Nature\'s aesthetic growth ratio.', emoji: '✨' }, { id: 'm1-2', type: 'explanation', title: 'Spirals', content: 'Found in seeds, shells, and hurricanes.', emoji: '🐚' }, { id: 'm1-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Your credit card is a golden rectangle.', emoji: '🤯', highlight: 'credit card is a golden rectangle' }, { id: 'm1-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Mathematical foundation of beauty.', emoji: '🔑' }] },
  { id: 'math-2', topicId: 'math', title: 'Zero', subtitle: 'Game Changer', duration: 3, difficulty: 'beginner', order: 2, cards: [{ id: 'm2-1', type: 'fact', title: 'Indian Discovery', content: 'First used as a number in 5th century India.', emoji: '0️⃣' }, { id: 'm2-2', type: 'explanation', title: 'Place Value', content: 'Enabled place-value notation and algebra.', emoji: '🧮' }, { id: 'm2-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Derived from Arabic "sifr" meaning empty.', emoji: '🤯', highlight: 'Arabic sifr meaning empty' }, { id: 'm2-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Foundation of digital age.', emoji: '🔑' }] },
  { id: 'math-3', topicId: 'math', title: 'Infinity', subtitle: 'Endlessness', duration: 5, difficulty: 'advanced', order: 3, cards: [{ id: 'm3-1', type: 'fact', title: 'Concept', content: 'Infinity is a concept of endlessness, not a number.', emoji: '♾️' }, { id: 'm3-2', type: 'explanation', title: 'Cantor Proof', content: 'Real numbers are a bigger infinity than counting numbers.', emoji: '🤯' }, { id: 'm3-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Cantor\'s work was initially mocked as a disease.', emoji: '🤯', highlight: 'initially mocked as a disease' }, { id: 'm3-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Essential to calculus.', emoji: '🔑' }] },
  { id: 'biology-1', topicId: 'biology', title: 'DNA Code', subtitle: 'Double helix', duration: 4, difficulty: 'beginner', order: 1, cards: [{ id: 'b1-1', type: 'fact', title: 'Structure', content: 'Twisted double helix ladder carrying genetic code.', emoji: '🧬' }, { id: 'b1-2', type: 'explanation', title: 'Four Bases', content: 'Encoded using A, T, C, and G chemical bases.', emoji: '🔤' }, { id: 'b1-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Uncoiled body DNA reaches Sun 600 times.', emoji: '🤯', highlight: 'reaches Sun 600 times' }, { id: 'b1-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Universal code of life.', emoji: '🔑' }] },
  { id: 'biology-2', topicId: 'biology', title: 'Photosynthesis', subtitle: 'Plant power', duration: 3, difficulty: 'beginner', order: 2, cards: [{ id: 'b2-1', type: 'fact', title: 'Solar Energy', content: 'Converts light + CO₂ + H₂O into glucose and oxygen.', emoji: '🌱' }, { id: 'b2-2', type: 'explanation', title: 'Chlorophyll', content: 'Reflects green light while absorbing red and blue.', emoji: '🟢' }, { id: 'b2-3', type: 'didYouKnow', title: 'Did You Know?', content: '70% of Earth\'s oxygen comes from ocean plankton.', emoji: '🤯', highlight: '70% oxygen from ocean plankton' }, { id: 'b2-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Feeds Earth food chain.', emoji: '🔑' }] },
  { id: 'biology-3', topicId: 'biology', title: 'Human Brain', subtitle: '86B neurons', duration: 4, difficulty: 'intermediate', order: 3, cards: [{ id: 'b3-1', type: 'fact', title: '86 Billion Neurons', content: 'Uses 20% of total body energy.', emoji: '🧠' }, { id: 'b3-2', type: 'explanation', title: 'Neuroplasticity', content: 'Rewires neural connections through learning.', emoji: '🔄' }, { id: 'b3-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Generates 12-25W of power—enough for an LED bulb.', emoji: '🤯', highlight: 'enough for an LED bulb' }, { id: 'b3-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Learning physically changes brain structure.', emoji: '🔑' }] },
  { id: 'geography-1', topicId: 'geography', title: 'Mariana Trench', subtitle: '36,070 ft deep', duration: 3, difficulty: 'beginner', order: 1, cards: [{ id: 'g1-1', type: 'fact', title: 'Depth', content: 'Challenger Deep is deeper than Everest is tall.', emoji: '🌊' }, { id: 'g1-2', type: 'explanation', title: 'Subduction', content: 'Formed by Pacific plate sliding under Mariana plate.', emoji: '🪨' }, { id: 'g1-3', type: 'didYouKnow', title: 'Did You Know?', content: 'More people walked on Moon than visited Challenger Deep.', emoji: '🤯', highlight: 'More people walked on Moon' }, { id: 'g1-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Oceans remain largely unexplored.', emoji: '🔑' }] },
  { id: 'geography-2', topicId: 'geography', title: 'Amazon Rainforest', subtitle: 'Ecosystem', duration: 4, difficulty: 'beginner', order: 2, cards: [{ id: 'g2-1', type: 'fact', title: 'Biodiversity', content: 'Home to 10% of all species on Earth.', emoji: '🌳' }, { id: 'g2-2', type: 'explanation', title: 'Flying Rivers', content: 'Transpiration creates atmospheric water rivers.', emoji: '💧' }, { id: 'g2-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Zero bridges cross the 4,000-mile Amazon river.', emoji: '🤯', highlight: 'Zero bridges cross the river' }, { id: 'g2-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Planetary life-support system.', emoji: '🔑' }] },
  { id: 'geography-3', topicId: 'geography', title: 'Plate Tectonics', subtitle: 'Moving crust', duration: 4, difficulty: 'intermediate', order: 3, cards: [{ id: 'g3-1', type: 'fact', title: 'Drift Speed', content: 'Plates move 1-10 cm per year.', emoji: '🌍' }, { id: 'g3-2', type: 'explanation', title: 'Pangaea', content: 'Supercontinent 200 million years ago.', emoji: '🧩' }, { id: 'g3-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Theory was mocked for decades until 1960s.', emoji: '🤯', highlight: 'mocked for decades' }, { id: 'g3-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Shapes mountains and quakes.', emoji: '🔑' }] },
  { id: 'space-1', topicId: 'space', title: 'Black Holes', subtitle: 'Gravity trap', duration: 4, difficulty: 'beginner', order: 1, cards: [{ id: 'sp1-1', type: 'fact', title: 'Extreme Gravity', content: 'Gravity so strong that light cannot escape.', emoji: '🕳️' }, { id: 'sp1-2', type: 'explanation', title: 'Event Horizon', content: 'The point of no return around a black hole.', emoji: '⚫' }, { id: 'sp1-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Compressed Earth black hole is marble-sized.', emoji: '🤯', highlight: 'compressed Earth is marble-sized' }, { id: 'sp1-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Warps space and time.', emoji: '🔑' }] },
  { id: 'space-2', topicId: 'space', title: 'Mars Planet', subtitle: 'Red soil', duration: 3, difficulty: 'beginner', order: 2, cards: [{ id: 'sp2-1', type: 'fact', title: 'Martian Sol', content: 'Day is 24h 37m; year is 687 days.', emoji: '🔴' }, { id: 'sp2-2', type: 'explanation', title: 'Rust Soil', content: 'Iron oxide gives Mars its red hue.', emoji: '🟤' }, { id: 'sp2-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Olympus Mons is 3x the height of Everest.', emoji: '🤯', highlight: '3x the height of Everest' }, { id: 'sp2-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Most viable human colonization candidate.', emoji: '🔑' }] },
  { id: 'space-3', topicId: 'space', title: 'Big Bang', subtitle: '13.8B years ago', duration: 5, difficulty: 'intermediate', order: 3, cards: [{ id: 'sp3-1', type: 'fact', title: 'Singularity', content: 'Universe expanded from an infinitely dense point.', emoji: '💥' }, { id: 'sp3-2', type: 'explanation', title: 'Space Expansion', content: 'Expansion OF space, not explosion IN space.', emoji: '🎈' }, { id: 'sp3-3', type: 'didYouKnow', title: 'Did You Know?', content: '1% of analog TV static is CMB radiation.', emoji: '🤯', highlight: '1% of analog TV static' }, { id: 'sp3-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Origin of universe.', emoji: '🔑' }] },
  { id: 'psychology-1', topicId: 'psychology', title: 'Dunning-Kruger', subtitle: 'Overestimating skill', duration: 3, difficulty: 'beginner', order: 1, cards: [{ id: 'p1-1', type: 'fact', title: 'Confidence Gap', content: 'Novices overestimate skill; experts underestimate theirs.', emoji: '📊' }, { id: 'p1-2', type: 'explanation', title: 'Unconscious Incompetence', content: 'Lacking knowledge prevents recognizing mistakes.', emoji: '📉' }, { id: 'p1-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Inspired by a bank robber who wore lemon juice.', emoji: '🤯', highlight: 'wore lemon juice' }, { id: 'p1-4', type: 'keyPoint', title: 'Key Takeaway', content: 'True wisdom comes with humility.', emoji: '🔑' }] },
  { id: 'psychology-2', topicId: 'psychology', title: 'Power of Habits', subtitle: 'Habit loop', duration: 4, difficulty: 'beginner', order: 2, cards: [{ id: 'p2-1', type: 'fact', title: 'Loop', content: 'Cue → Routine → Reward governs 40% of actions.', emoji: '🔁' }, { id: 'p2-2', type: 'explanation', title: 'Brain Automation', content: 'Automating behavior saves mental energy.', emoji: '⚙️' }, { id: 'p2-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Takes 66 days on average to form a habit.', emoji: '🤯', highlight: 'Takes 66 days on average' }, { id: 'p2-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Change routine to alter habit.', emoji: '🔑' }] },
  { id: 'psychology-3', topicId: 'psychology', title: 'Memory & Forgetting', subtitle: 'Forgetting curve', duration: 4, difficulty: 'intermediate', order: 3, cards: [{ id: 'p3-1', type: 'fact', title: '70% Lost', content: 'We forget 70% of new information within 24 hours.', emoji: '📉' }, { id: 'p3-2', type: 'explanation', title: 'Spaced Review', content: 'Review at expanding intervals to lock memories in.', emoji: '📅' }, { id: 'p3-3', type: 'didYouKnow', title: 'Did You Know?', content: 'Deep sleep consolidates memories into long term storage.', emoji: '🤯', highlight: 'consolidates memories into long term' }, { id: 'p3-4', type: 'keyPoint', title: 'Key Takeaway', content: 'Spaced repetition + sleep.', emoji: '🔑' }] },
];

// ============ QUIZZES ============
export const QUIZZES: Quiz[] = [
  { id: 'quiz-social-1', lessonId: 'social-1', topicId: 'social-skills', questions: [{ id: 'qsoc1-1', type: 'multiple_choice', question: 'How long does a first impression take?', options: ['30s', '7 seconds', '2m', '5m'], correctIndex: 1, explanation: 'Formed within 7 seconds.' }, { id: 'qsoc1-2', type: 'true_false', question: 'Words make up 90% of impression.', options: ['True', 'False'], correctIndex: 1, explanation: 'Tone & body language make up over 90%.' }, { id: 'qsoc1-3', type: 'multiple_choice', question: 'How much does saying someone\'s name twice boost warmth?', options: ['10%', '20%', '38%', '75%'], correctIndex: 2, explanation: 'Saying name 2x increases warmth by 38%.' }] },
  { id: 'quiz-comm-first-contact', lessonId: 'comm-first-contact', topicId: 'communication', questions: [{ id: 'qcfc-1', type: 'multiple_choice', question: 'Best first contact opener?', options: ['Scripted line', 'Contextual observation about shared space', 'Weather complaint', 'Asking money'], correctIndex: 1, explanation: 'Contextual observations feel natural.' }, { id: 'qcfc-2', type: 'true_false', question: 'Warm statement reduces tension by 45%.', options: ['True', 'False'], correctIndex: 0, explanation: 'Statements require zero pressure to respond.' }, { id: 'qcfc-3', type: 'multiple_choice', question: 'Better than "what do you do"?', options: ['"How much money?"', '"What are you working on that you\'re excited about?"', '"Why alone?"', '"Age?"'], correctIndex: 1, explanation: 'Unlocks passion and story.' }] },
  { id: 'quiz-comm-small-talk', lessonId: 'comm-small-talk', topicId: 'communication', questions: [{ id: 'qcst-1', type: 'multiple_choice', question: 'FORD stands for?', options: ['Fast Open', 'Family, Occupation, Recreation, Dreams', 'Food Outdoor', 'Facts Options'], correctIndex: 1, explanation: 'Family, Occupation, Recreation, Dreams.' }, { id: 'qcst-2', type: 'true_false', question: 'Tiny personal detail builds 2x rapport.', options: ['True', 'False'], correctIndex: 0, explanation: 'Small vulnerability fosters fast connection.' }, { id: 'qcst-3', type: 'multiple_choice', question: 'Conversational Threading?', options: ['Sewing', 'Expanding on keywords from partner\'s sentence', 'Talking over', 'Abrupt change'], correctIndex: 1, explanation: 'Pulls keywords to expand topics.' }] },
  { id: 'quiz-comm-nice-person', lessonId: 'comm-nice-person', topicId: 'communication', questions: [{ id: 'qcnp-1', type: 'multiple_choice', question: 'Replace "Sorry for being late"?', options: ['"Don\'t care"', '"Thank you for your patience!"', '"Sorry sorry"', '"Traffic"'], correctIndex: 1, explanation: 'Reframing to gratitude builds status.' }, { id: 'qcnp-2', type: 'true_false', question: 'Upspeak increases authority.', options: ['True', 'False'], correctIndex: 1, explanation: 'Upspeak drops authority by 30%.' }, { id: 'qcnp-3', type: 'multiple_choice', question: 'High status communication?', options: ['Rude', 'Over-apologizing', 'Combining warmth with non-apologetic directness', 'Silence'], correctIndex: 2, explanation: 'Warmth + directness.' }] },
  { id: 'quiz-comm-networking', lessonId: 'comm-networking', topicId: 'communication', questions: [{ id: 'qcnet-1', type: 'multiple_choice', question: 'Open group formation?', options: ['Closed circle', 'V-shape formation', 'Whispering pair', 'Wall facers'], correctIndex: 1, explanation: 'V-shape indicates open entrance.' }, { id: 'qcnet-2', type: 'true_false', question: '90% feel uncomfortable initiating.', options: ['True', 'False'], correctIndex: 0, explanation: 'Initiating is appreciated.' }, { id: 'qcnet-3', type: 'multiple_choice', question: 'Exit formula?', options: ['Fainting', 'Value + Transition formula', 'Screaming', 'Ignoring'], correctIndex: 1, explanation: 'Value + Transition.' }] },
  { id: 'quiz-tech-digital-money', lessonId: 'tech-digital-money', topicId: 'technology', questions: [{ id: 'qtdm-1', type: 'multiple_choice', question: 'What controls crypto networks?', options: ['Central Banks', 'Peer-to-peer computer networks & cryptography', 'World Bank', 'Single CEO'], correctIndex: 1, explanation: 'Decentralized peer-to-peer networks.' }, { id: 'qtdm-2', type: 'true_false', question: 'Verified blockchain blocks can be altered.', options: ['True', 'False'], correctIndex: 1, explanation: 'Blockchain ledgers are immutable.' }, { id: 'qtdm-3', type: 'multiple_choice', question: 'Hard-coded Bitcoin limit?', options: ['10 million', '21 million', '100 million', 'Unlimited'], correctIndex: 1, explanation: 'Hard-capped at 21 million.' }] },
  { id: 'quiz-social-2', lessonId: 'social-2', topicId: 'social-skills', questions: [{ id: 'qsoc2-1', type: 'multiple_choice', question: 'Mirror Technique?', options: ['Mirror looking', 'Repeat last 2-3 words', 'Matching clothes', 'Interrupting'], correctIndex: 1, explanation: 'Repeat last 2-3 words.' }, { id: 'qsoc2-2', type: 'true_false', question: 'Pausing 2s looks weak.', options: ['True', 'False'], correctIndex: 1, explanation: 'Makes you look 40% more thoughtful.' }, { id: 'qsoc2-3', type: 'multiple_choice', question: 'Most focus in chats?', options: ['Understanding', 'Planning reply', 'Counting words', 'Body language'], correctIndex: 1, explanation: 'Planning reply.' }] },
  { id: 'quiz-social-3', lessonId: 'social-3', topicId: 'social-skills', questions: [{ id: 'qsoc3-1', type: 'multiple_choice', question: 'Spotlight Effect?', options: ['Fame', 'Overestimating flaw notice', 'Stage faint', 'Skin glow'], correctIndex: 1, explanation: 'Overestimating judgment.' }, { id: 'qsoc3-2', type: 'true_false', question: 'Power posing lowers stress.', options: ['True', 'False'], correctIndex: 0, explanation: 'Lowers cortisol 25%.' }, { id: 'qsoc3-3', type: 'multiple_choice', question: 'Calm social anxiety by?', options: ['Monitor heart rate', 'Shift attention outward to room', 'Fidget', 'Leave'], correctIndex: 1, explanation: 'Shift focus outward.' }] },
  { id: 'quiz-growth-1', lessonId: 'growth-1', topicId: 'personal-growth', questions: [{ id: 'qpg1-1', type: 'multiple_choice', question: 'Procrastination root?', options: ['Time', 'Emotion regulation', 'Clocks', 'IQ'], correctIndex: 1, explanation: 'Emotional regulation.' }, { id: 'qpg1-2', type: 'true_false', question: '2-minute commitment.', options: ['True', 'False'], correctIndex: 0, explanation: 'Reduces friction.' }, { id: 'qpg1-3', type: 'multiple_choice', question: 'Zeigarnik Effect?', options: ['Finished', 'Unfinished active', 'Sugar', 'Sleep'], correctIndex: 1, explanation: 'Unfinished active.' }] },
  { id: 'quiz-growth-2', lessonId: 'growth-2', topicId: 'personal-growth', questions: [{ id: 'qpg2-1', type: 'multiple_choice', question: '1% daily for 1 year?', options: ['365%', '37x better', '2x', '10%'], correctIndex: 1, explanation: '37x better.' }, { id: 'qpg2-2', type: 'true_false', question: 'Willpower > Environment.', options: ['True', 'False'], correctIndex: 1, explanation: 'Environment 5x.' }, { id: 'qpg2-3', type: 'multiple_choice', question: 'Habit Stacking?', options: ['5 habits', 'Pairing new to routine', 'Books', 'Breaking'], correctIndex: 1, explanation: 'Pair to routine.' }] },
  { id: 'quiz-growth-3', lessonId: 'growth-3', topicId: 'personal-growth', questions: [{ id: 'qpg3-1', type: 'multiple_choice', question: 'Focus recovery time?', options: ['2 min', '5 min', '23 min', '1 hour'], correctIndex: 2, explanation: '23 minutes.' }, { id: 'qpg3-2', type: 'true_false', question: 'Attention residue.', options: ['True', 'False'], correctIndex: 0, explanation: 'True.' }, { id: 'qpg3-3', type: 'multiple_choice', question: 'Deep work block?', options: ['15 min', '90 min', '6 hours', '24 hours'], correctIndex: 1, explanation: '90 minutes.' }] },
  { id: 'quiz-philosophy-1', lessonId: 'philosophy-1', topicId: 'philosophy', questions: [{ id: 'qph1-1', type: 'multiple_choice', question: 'Stoic control?', options: ['Weather', 'Opinions', 'Own thoughts & reactions', 'Stocks'], correctIndex: 2, explanation: 'Own mind.' }, { id: 'qph1-2', type: 'true_false', question: 'Amor Fati.', options: ['True', 'False'], correctIndex: 1, explanation: 'Love fate.' }, { id: 'qph1-3', type: 'multiple_choice', question: 'Meditations author?', options: ['Socrates', 'Marcus Aurelius', 'Plato', 'Nietzsche'], correctIndex: 1, explanation: 'Marcus Aurelius.' }] },
  { id: 'quiz-philosophy-2', lessonId: 'philosophy-2', topicId: 'philosophy', questions: [{ id: 'qph2-1', type: 'multiple_choice', question: 'Inversion Thinking?', options: ['Upside down', 'Guaranteed failure avoidance', 'Color', 'Facts'], correctIndex: 1, explanation: 'Avoid failure.' }, { id: 'qph2-2', type: 'true_false', question: 'First principles = copying.', options: ['True', 'False'], correctIndex: 1, explanation: 'Fundamental truths.' }, { id: 'qph2-3', type: 'multiple_choice', question: 'Mental models investors?', options: ['Buffett & Munger', 'Jobs', 'Edison', 'Newton'], correctIndex: 0, explanation: 'Buffett & Munger.' }] },
  { id: 'quiz-philosophy-3', lessonId: 'philosophy-3', topicId: 'philosophy', questions: [{ id: 'qph3-1', type: 'multiple_choice', question: 'Occam\'s Razor?', options: ['Shaving', 'Simplest explanation', 'Hardest', 'No data'], correctIndex: 1, explanation: 'Simplest.' }, { id: 'qph3-2', type: 'true_false', question: 'Ad Hominem.', options: ['True', 'False'], correctIndex: 0, explanation: 'Attacks person.' }, { id: 'qph3-3', type: 'multiple_choice', question: 'Confirmation Bias?', options: ['Flight', 'Filtering contradicting info', 'Open', 'Remembering'], correctIndex: 1, explanation: 'Filters opposing info.' }] },
  { id: 'quiz-business-1', lessonId: 'business-1', topicId: 'business', questions: [{ id: 'qbiz1-1', type: 'multiple_choice', question: 'Tactical Empathy?', options: ['Pity', 'Understanding mindset', 'Giving up', 'Crying'], correctIndex: 1, explanation: 'Understanding mindset.' }, { id: 'qbiz1-2', type: 'true_false', question: '"No" feels safe.', options: ['True', 'False'], correctIndex: 0, explanation: 'Protects autonomy.' }, { id: 'qbiz1-3', type: 'multiple_choice', question: 'Negotiation question?', options: ['Yes/No', 'Calibrated How/What', 'Multiple', 'Demands'], correctIndex: 1, explanation: 'Calibrated How/What.' }] },
  { id: 'quiz-business-2', lessonId: 'business-2', topicId: 'business', questions: [{ id: 'qbiz2-1', type: 'multiple_choice', question: 'Rule of 72?', options: ['Taxes', 'Doubling time', '72-day', 'Stocks'], correctIndex: 1, explanation: 'Doubling time.' }, { id: 'qbiz2-2', type: 'true_false', question: 'Buffett before 30.', options: ['True', 'False'], correctIndex: 1, explanation: '99% after 50.' }, { id: 'qbiz2-3', type: 'multiple_choice', question: 'Compound interest?', options: ['Principal only', 'Interest on interest', 'Penalty', 'Fixed'], correctIndex: 1, explanation: 'Interest on interest.' }] },
  { id: 'quiz-business-3', lessonId: 'business-3', topicId: 'business', questions: [{ id: 'qbiz3-1', type: 'multiple_choice', question: 'MVP?', options: ['Expensive', 'Simplest for learning', 'Finished', 'Plan'], correctIndex: 1, explanation: 'Simplest for learning.' }, { id: 'qbiz3-2', type: 'true_false', question: 'Lean loop.', options: ['True', 'False'], correctIndex: 0, explanation: 'Build Measure Learn.' }, { id: 'qbiz3-3', type: 'multiple_choice', question: 'Airbnb MVP?', options: ['App', 'Blog air mattress', 'Hotel', 'TV'], correctIndex: 1, explanation: 'Air mattresses on blog.' }] },
  { id: 'quiz-health-1', lessonId: 'health-1', topicId: 'health', questions: [{ id: 'qhea1-1', type: 'multiple_choice', question: 'Morning light hormone?', options: ['Melatonin', 'Cortisol', 'Insulin', 'Adrenaline'], correctIndex: 1, explanation: 'Cortisol.' }, { id: 'qhea1-2', type: 'true_false', question: 'Glymphatic sleep.', options: ['True', 'False'], correctIndex: 0, explanation: 'Clears brain waste.' }, { id: 'qhea1-3', type: 'multiple_choice', question: 'Sleep temp?', options: ['75°F', '65°F', '50°F', '80°F'], correctIndex: 1, explanation: '~65°F.' }] },
  { id: 'quiz-health-2', lessonId: 'health-2', topicId: 'health', questions: [{ id: 'qhea2-1', type: 'multiple_choice', question: 'Physiological Sigh?', options: ['1m hold', '2 inhales + 1 long exhale', 'Hyperventilate', 'Scream'], correctIndex: 1, explanation: '2 inhales + 1 long exhale.' }, { id: 'qhea2-2', type: 'true_false', question: 'Shrinks amygdala.', options: ['True', 'False'], correctIndex: 0, explanation: 'Shrinks amygdala.' }, { id: 'qhea2-3', type: 'multiple_choice', question: 'Threat center?', options: ['Prefrontal', 'Amygdala', 'Hippocampus', 'Cerebellum'], correctIndex: 1, explanation: 'Amygdala.' }] },
  { id: 'quiz-health-3', lessonId: 'health-3', topicId: 'health', questions: [{ id: 'qhea3-1', type: 'multiple_choice', question: 'Serotonin site?', options: ['Brain', 'Gut microbiome', 'Liver', 'Heart'], correctIndex: 1, explanation: '90% in gut.' }, { id: 'qhea3-2', type: 'true_false', question: 'Ultra-processed food.', options: ['True', 'False'], correctIndex: 0, explanation: 'Bliss point.' }, { id: 'qhea3-3', type: 'multiple_choice', question: 'Macronutrient?', options: ['Vitamin C', 'Protein', 'Zinc', 'Iron'], correctIndex: 1, explanation: 'Protein.' }] },
  { id: 'quiz-tech-1', lessonId: 'tech-1', topicId: 'technology', questions: [{ id: 'qtec1-1', type: 'multiple_choice', question: 'LLM output generation?', options: ['Sentient thought', 'Predicting next token', 'Google search only', 'Human agent'], correctIndex: 1, explanation: 'Next token prediction.' }, { id: 'qtec1-2', type: 'true_false', question: 'Transformers introduced in 2017.', options: ['True', 'False'], correctIndex: 0, explanation: 'Transformer paper in 2017.' }, { id: 'qtec1-3', type: 'multiple_choice', question: 'Modern AI description?', options: ['Conscious mind', 'Pattern recognition multiplier', 'Magic', 'Drive'], correctIndex: 1, explanation: 'Pattern recognition engine.' }] },
  { id: 'quiz-tech-2', lessonId: 'tech-2', topicId: 'technology', questions: [{ id: 'qtec2-1', type: 'multiple_choice', question: 'Human error in breaches?', options: ['10%', '30%', 'Over 80%', '100%'], correctIndex: 2, explanation: 'Over 80% human error.' }, { id: 'qtec2-2', type: 'true_false', question: '14-char passphrase takes 100k yrs.', options: ['True', 'False'], correctIndex: 0, explanation: 'Exponential difficulty.' }, { id: 'qtec2-3', type: 'multiple_choice', question: 'Safest password storage?', options: ['Sticky note', 'Browser sheet', 'Encrypted manager + 2FA', 'Reuse one'], correctIndex: 2, explanation: 'Password manager + 2FA.' }] },
  { id: 'quiz-tech-3', lessonId: 'tech-3', topicId: 'technology', questions: [{ id: 'qtec3-1', type: 'multiple_choice', question: 'Quantum computing units?', options: ['Bits', 'Bytes', 'Qubits', 'Photons'], correctIndex: 2, explanation: 'Qubits.' }, { id: 'qtec3-2', type: 'true_false', question: 'Superposition allows parallel states.', options: ['True', 'False'], correctIndex: 0, explanation: 'Parallel state calculation.' }, { id: 'qtec3-3', type: 'multiple_choice', question: 'Einstein name for entanglement?', options: ['Relativity', 'Spooky action at a distance', 'Quantum leap', 'Dark matter'], correctIndex: 1, explanation: 'Spooky action at a distance.' }] },
  { id: 'quiz-history-1', lessonId: 'history-1', topicId: 'history', questions: [{ id: 'qh1-1', type: 'multiple_choice', question: 'Year Rome fell?', options: ['330 AD', '476 AD', '1453 AD', '27 BC'], correctIndex: 1, explanation: '476 AD.' }, { id: 'qh1-2', type: 'true_false', question: 'Eastern Rome fell same time.', options: ['True', 'False'], correctIndex: 1, explanation: '1453.' }, { id: 'qh1-3', type: 'multiple_choice', question: 'Rome % world pop?', options: ['5%', '10%', '21%', '50%'], correctIndex: 2, explanation: '21%.' }] },
  { id: 'quiz-history-2', lessonId: 'history-2', topicId: 'history', questions: [{ id: 'qh2-1', type: 'multiple_choice', question: 'Silk road length?', options: ['1k', '2k', '4k mi', '10k'], correctIndex: 2, explanation: '4,000 mi.' }, { id: 'qh2-2', type: 'true_false', question: 'Term by ancient travelers.', options: ['True', 'False'], correctIndex: 1, explanation: 'Coined 1877.' }, { id: 'qh2-3', type: 'multiple_choice', question: 'Not on Silk road?', options: ['Buddhism', 'Silk', 'Internet', 'Islam'], correctIndex: 2, explanation: 'Internet.' }] },
  { id: 'quiz-history-3', lessonId: 'history-3', topicId: 'history', questions: [{ id: 'qh3-1', type: 'multiple_choice', question: 'French rev start?', options: ['Execution', 'Bastille', 'Versailles', 'March'], correctIndex: 1, explanation: 'Bastille.' }, { id: 'qh3-2', type: 'true_false', question: 'Marie Antoinette cake.', options: ['True', 'False'], correctIndex: 1, explanation: 'False.' }, { id: 'qh3-3', type: 'multiple_choice', question: 'Third estate %?', options: ['33%', '50%', '75%', '98%'], correctIndex: 3, explanation: '98%.' }] },
  { id: 'quiz-science-1', lessonId: 'science-1', topicId: 'science', questions: [{ id: 'qs1-1', type: 'multiple_choice', question: 'Gravity by Einstein?', options: ['Magnetic', 'Spacetime curvature', 'Electric', 'Nuclear'], correctIndex: 1, explanation: 'Spacetime curvature.' }, { id: 'qs1-2', type: 'true_false', question: 'Gravity strongest.', options: ['True', 'False'], correctIndex: 1, explanation: 'Weakest.' }, { id: 'qs1-3', type: 'multiple_choice', question: 'Fling speed?', options: ['100', '500', '1,000 mph', '5,000'], correctIndex: 2, explanation: '1,000 mph.' }] },
  { id: 'quiz-science-2', lessonId: 'science-2', topicId: 'science', questions: [{ id: 'qs2-1', type: 'multiple_choice', question: '% plasma?', options: ['10%', '50%', '75%', '99%'], correctIndex: 3, explanation: '99%.' }, { id: 'qs2-2', type: 'true_false', question: 'Glass liquid.', options: ['True', 'False'], correctIndex: 1, explanation: 'Solid.' }, { id: 'qs2-3', type: 'multiple_choice', question: 'State factor?', options: ['Color', 'Kinetic energy', 'Weight', 'Shape'], correctIndex: 1, explanation: 'Kinetic energy.' }] },
  { id: 'quiz-science-3', lessonId: 'science-3', topicId: 'science', questions: [{ id: 'qs3-1', type: 'multiple_choice', question: 'Sunlight time?', options: ['1m', '8m 20s', '1h', '1s'], correctIndex: 1, explanation: '8m 20s.' }, { id: 'qs3-2', type: 'true_false', question: 'Mass at light speed.', options: ['True', 'False'], correctIndex: 1, explanation: 'Infinite energy.' }, { id: 'qs3-3', type: 'multiple_choice', question: 'Earth orbits by light/sec?', options: ['1', '3.5', '7.5', '100'], correctIndex: 2, explanation: '7.5.' }] },
  { id: 'quiz-art-1', lessonId: 'art-1', topicId: 'art', questions: [{ id: 'qa1-1', type: 'multiple_choice', question: 'Smile technique?', options: ['Chiaroscuro', 'Sfumato', 'Pointillism', 'Fresco'], correctIndex: 1, explanation: 'Sfumato.' }, { id: 'qa1-2', type: 'true_false', question: 'Famous instantly.', options: ['True', 'False'], correctIndex: 1, explanation: 'Stolen 1911.' }, { id: 'qa1-3', type: 'multiple_choice', question: 'Size?', options: ['3x2 ft', '30x21 in', '5x3 ft', '10x7 ft'], correctIndex: 1, explanation: '30x21 in.' }] },
  { id: 'quiz-art-2', lessonId: 'art-2', topicId: 'art', questions: [{ id: 'qa2-1', type: 'multiple_choice', question: 'Impressionism enabler?', options: ['Camera', 'Paint tube', 'Bulb', 'Canvas'], correctIndex: 1, explanation: 'Paint tube.' }, { id: 'qa2-2', type: 'true_false', question: 'Name compliment.', options: ['True', 'False'], correctIndex: 1, explanation: 'Insult.' }, { id: 'qa2-3', type: 'multiple_choice', question: 'Origin?', options: ['London', 'NY', 'Paris', 'Rome'], correctIndex: 2, explanation: 'Paris.' }] },
  { id: 'quiz-art-3', lessonId: 'art-3', topicId: 'art', questions: [{ id: 'qa3-1', type: 'multiple_choice', question: 'Ukiyo-e meaning?', options: ['Beauty', 'Floating world pictures', 'Mountain', 'Imperial'], correctIndex: 1, explanation: 'Floating world pictures.' }, { id: 'qa3-2', type: 'true_false', question: 'Packing paper.', options: ['True', 'False'], correctIndex: 0, explanation: 'Wrapping.' }, { id: 'qa3-3', type: 'multiple_choice', question: 'Great Wave?', options: ['Monet', 'Hokusai', 'Hiroshige', 'Van Gogh'], correctIndex: 1, explanation: 'Hokusai.' }] },
  { id: 'quiz-math-1', lessonId: 'math-1', topicId: 'math', questions: [{ id: 'qm1-1', type: 'multiple_choice', question: 'Golden ratio φ?', options: ['1.414', '1.618', '2.718', '3.14'], correctIndex: 1, explanation: '1.618.' }, { id: 'qm1-2', type: 'true_false', question: 'Credit card.', options: ['True', 'False'], correctIndex: 0, explanation: 'True.' }, { id: 'qm1-3', type: 'multiple_choice', question: 'Not in golden ratio?', options: ['Nautilus', 'Sunflower', 'Binary', 'Parthenon'], correctIndex: 2, explanation: 'Binary.' }] },
  { id: 'quiz-math-2', lessonId: 'math-2', topicId: 'math', questions: [{ id: 'qm2-1', type: 'multiple_choice', question: 'Zero origin?', options: ['Greek', 'Roman', 'Indian', 'Egyptian'], correctIndex: 2, explanation: 'Indian.' }, { id: 'qm2-2', type: 'true_false', question: 'Latin origin.', options: ['True', 'False'], correctIndex: 1, explanation: 'Arabic sifr.' }, { id: 'qm2-3', type: 'multiple_choice', question: 'Zero enabled?', options: ['Color', 'Place value', 'Music', 'Calendar'], correctIndex: 1, explanation: 'Place value.' }] },
  { id: 'quiz-math-3', lessonId: 'math-3', topicId: 'math', questions: [{ id: 'qm3-1', type: 'multiple_choice', question: '∞ - ∞?', options: ['0', '∞', '1', 'Undefined'], correctIndex: 3, explanation: 'Undefined.' }, { id: 'qm3-2', type: 'true_false', question: 'All infinities equal.', options: ['True', 'False'], correctIndex: 1, explanation: 'Cantor.' }, { id: 'qm3-3', type: 'multiple_choice', question: 'Larger infinity?', options: ['Counting', 'Evens', 'Reals', 'Equal'], correctIndex: 2, explanation: 'Reals.' }] },
  { id: 'quiz-biology-1', lessonId: 'biology-1', topicId: 'biology', questions: [{ id: 'qb1-1', type: 'multiple_choice', question: 'DNA bases?', options: ['2', '4', '8', '26'], correctIndex: 1, explanation: '4.' }, { id: 'qb1-2', type: 'true_false', question: 'Sun 600x.', options: ['True', 'False'], correctIndex: 0, explanation: 'True.' }, { id: 'qb1-3', type: 'multiple_choice', question: 'Shape?', options: ['Triple', 'Double helix', 'Single', 'Loop'], correctIndex: 1, explanation: 'Double helix.' }] },
  { id: 'quiz-biology-2', lessonId: 'biology-2', topicId: 'biology', questions: [{ id: 'qb2-1', type: 'multiple_choice', question: 'Marine O₂ %?', options: ['20%', '40%', '70%', '90%'], correctIndex: 2, explanation: '70%.' }, { id: 'qb2-2', type: 'true_false', question: 'Absorbs green.', options: ['True', 'False'], correctIndex: 1, explanation: 'Reflects green.' }, { id: 'qb2-3', type: 'multiple_choice', question: 'Inputs?', options: ['O₂ & glucose', 'CO₂, water, light', 'Nitrogen', 'O₂'], correctIndex: 1, explanation: 'CO₂, water, light.' }] },
  { id: 'quiz-biology-3', lessonId: 'biology-3', topicId: 'biology', questions: [{ id: 'qb3-1', type: 'multiple_choice', question: 'Neuron count?', options: ['1M', '86M', '86B', '1T'], correctIndex: 2, explanation: '86B.' }, { id: 'qb3-2', type: 'true_false', question: 'Uses 20% energy.', options: ['True', 'False'], correctIndex: 0, explanation: 'True.' }, { id: 'qb3-3', type: 'multiple_choice', question: 'Neuroplasticity?', options: ['Surgery', 'Rewiring', 'Disease', 'Size'], correctIndex: 1, explanation: 'Rewiring.' }] },
  { id: 'quiz-geography-1', lessonId: 'geography-1', topicId: 'geography', questions: [{ id: 'qg1-1', type: 'multiple_choice', question: 'Trench depth?', options: ['10k', '20k', '36,070 ft', '50k'], correctIndex: 2, explanation: '36,070 ft.' }, { id: 'qg1-2', type: 'true_false', question: 'More bottom visitors than Moon.', options: ['True', 'False'], correctIndex: 1, explanation: '3 vs 12.' }, { id: 'qg1-3', type: 'multiple_choice', question: 'Origin?', options: ['Volcano', 'Asteroid', 'Subduction', 'River'], correctIndex: 2, explanation: 'Subduction.' }] },
  { id: 'quiz-geography-2', lessonId: 'geography-2', topicId: 'geography', questions: [{ id: 'qg2-1', type: 'multiple_choice', question: 'Amazon bridges?', options: ['Zero', '3', '12', 'Hundreds'], correctIndex: 0, explanation: 'Zero.' }, { id: 'qg2-2', type: 'true_false', question: '10% species.', options: ['True', 'False'], correctIndex: 0, explanation: 'True.' }, { id: 'qg2-3', type: 'multiple_choice', question: 'Countries?', options: ['3', '5', '9', '12'], correctIndex: 2, explanation: '9.' }] },
  { id: 'quiz-geography-3', lessonId: 'geography-3', topicId: 'geography', questions: [{ id: 'qg3-1', type: 'multiple_choice', question: 'Plate speed?', options: ['1-10 cm/yr', '1-10 m/yr', '1-10 km/yr', 'No'], correctIndex: 0, explanation: '1-10 cm/yr.' }, { id: 'qg3-2', type: 'true_false', question: 'Accepted.', options: ['True', 'False'], correctIndex: 1, explanation: 'Mocked.' }, { id: 'qg3-3', type: 'multiple_choice', question: 'Supercontinent?', options: ['Atlantis', 'Gondwana', 'Pangaea', 'Laurentia'], correctIndex: 2, explanation: 'Pangaea.' }] },
  { id: 'quiz-space-1', lessonId: 'space-1', topicId: 'space', questions: [{ id: 'qsp1-1', type: 'multiple_choice', question: 'Point of no return?', options: ['Singularity', 'Event horizon', 'Accretion', 'Photon'], correctIndex: 1, explanation: 'Event horizon.' }, { id: 'qsp1-2', type: 'true_false', question: 'Earth black hole = basketball.', options: ['True', 'False'], correctIndex: 1, explanation: 'Marble size.' }, { id: 'qsp1-3', type: 'multiple_choice', question: 'Creation?', options: ['Collision', 'Star collapse', 'Dark energy', 'Supernova'], correctIndex: 1, explanation: 'Star collapse.' }] },
  { id: 'quiz-space-2', lessonId: 'space-2', topicId: 'space', questions: [{ id: 'qsp2-1', type: 'multiple_choice', question: 'Olympus Mons height?', options: ['10k', '29k', '72,000 ft', '100k'], correctIndex: 2, explanation: '72,000 ft.' }, { id: 'qsp2-2', type: 'true_false', question: 'Mars day close to Earth.', options: ['True', 'False'], correctIndex: 0, explanation: '24h 37m.' }, { id: 'qsp2-3', type: 'multiple_choice', question: 'Red color?', options: ['Sand', 'Iron oxide', 'Lava', 'Algae'], correctIndex: 1, explanation: 'Iron oxide.' }] },
  { id: 'quiz-space-3', lessonId: 'space-3', topicId: 'space', questions: [{ id: 'qsp3-1', type: 'multiple_choice', question: 'Age of universe?', options: ['4.5B', '8B', '13.8B yrs', '100B'], correctIndex: 2, explanation: '13.8 billion.' }, { id: 'qsp3-2', type: 'true_false', question: 'Explosion IN space.', options: ['True', 'False'], correctIndex: 1, explanation: 'Expansion OF space.' }, { id: 'qsp3-3', type: 'multiple_choice', question: 'Daily evidence?', options: ['TV static', 'Aurora', 'Rainbow', 'None'], correctIndex: 0, explanation: '1% analog TV static.' }] },
  { id: 'quiz-psychology-1', lessonId: 'psychology-1', topicId: 'psychology', questions: [{ id: 'qp1-1', type: 'multiple_choice', question: 'Dunning Kruger?', options: ['Experts overconfident', 'Novices underconfident', 'Limited knowledge overestimates skill', 'Perfect awareness'], correctIndex: 2, explanation: 'Limited knowledge overestimates.' }, { id: 'qp1-2', type: 'true_false', question: 'Lemon juice robber.', options: ['True', 'False'], correctIndex: 0, explanation: 'True.' }, { id: 'qp1-3', type: 'multiple_choice', question: 'Progression?', options: ['Up', 'Drops then rises', 'Constant', 'Down'], correctIndex: 1, explanation: 'Drops then rises.' }] },
  { id: 'quiz-psychology-2', lessonId: 'psychology-2', topicId: 'psychology', questions: [{ id: 'qp2-1', type: 'multiple_choice', question: 'Habit average time?', options: ['7d', '21d', '66 days', '365d'], correctIndex: 2, explanation: '66 days.' }, { id: 'qp2-2', type: 'true_false', question: '40% habits.', options: ['True', 'False'], correctIndex: 0, explanation: 'True.' }, { id: 'qp2-3', type: 'multiple_choice', question: 'Change habit?', options: ['Change cue', 'Change routine', 'Change reward', 'Stop thinking'], correctIndex: 1, explanation: 'Change the routine.' }] },
  { id: 'quiz-psychology-3', lessonId: 'psychology-3', topicId: 'psychology', questions: [{ id: 'qp3-1', type: 'multiple_choice', question: 'Forgetting in 24h?', options: ['10%', '30%', '50%', '70%'], correctIndex: 3, explanation: '70%.' }, { id: 'qp3-2', type: 'true_false', question: 'Sleep consolidates memories.', options: ['True', 'False'], correctIndex: 0, explanation: 'True.' }, { id: 'qp3-3', type: 'multiple_choice', question: 'Best retention method?', options: ['Read once', 'Spaced repetition', 'Highlight', 'Music'], correctIndex: 1, explanation: 'Spaced repetition.' }] },
];

// Helper functions
export function getTopicById(id: string): Topic | undefined {
  return TOPICS.find(t => t.id === id);
}

export function getLessonsByTopic(topicId: string): Lesson[] {
  return LESSONS.filter(l => l.topicId === topicId).sort((a, b) => a.order - b.order);
}

export function getLessonById(id: string): Lesson | undefined {
  return LESSONS.find(l => l.id === id);
}

export function getQuizByLessonId(lessonId: string): Quiz | undefined {
  return QUIZZES.find(q => q.lessonId === lessonId);
}
